### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by compyy** [lcristianiim/estimote-beacon-getter#1]
Sorry, can you please write detailed docs, how to use it, I want to do exactly same what you are doing.

Thanks.

**Comment by lcristianiim** [comment]
Hello @compyy, 
I did not made a documentation until now because this repository is basically a copy of the https://github.com/sandeepmistry/node-bleacon project, but I have created test.js that makes:
- getting data from BLE (Estimote Location Beacon) - temperature, pressure, light, rssi, etc..
- calculating the distance from BLE to reciever (in my case raspberry pi)
- posting the data to a server as JSON

In order to use it, you sould edit the [server settings](https://github.com/lcristianiim/estimote-beacon-getter/blob/master/test.js#L154) and then simply run the test.js with `sudo node test.js` (after 'npm i' of course)
The problem is that after a lot of hard work I could not get a correct distance from the BLE device. I wanted an approximation with an error 0.5 meters, but it seems that is not possible to do this due to the very big rssi fluctuations.
If you find a solution for calculating the accurate distance please share it. (I have tried everything I could find)
